# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
My_list=[5,5,5,5,5,5,5,5,5,5]
np.array(My_list)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,52,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
my_mat=[[0,1,2],[3,4,5],[6,7,8]]
np.array(my_mat)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand(1)

array([0.1078077])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [13]:
np.random.rand(25)

array([0.40468576, 0.27566152, 0.47836699, 0.50865046, 0.40556509,
       0.5719665 , 0.79128205, 0.98611246, 0.15539856, 0.92824207,
       0.62339751, 0.50490248, 0.20110026, 0.0646769 , 0.12836264,
       0.4712018 , 0.21857568, 0.1370341 , 0.58778836, 0.16188597,
       0.49290222, 0.88209537, 0.7465164 , 0.35694864, 0.45180162])

#### Create the following matrix:

In [26]:
np.arange(0,0.5,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [30]:
np.arange(0,1.0,0.05263158)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.2631579 , 0.31578948, 0.36842106, 0.42105264, 0.47368422,
       0.5263158 , 0.57894738, 0.63157896, 0.68421054, 0.73684212,
       0.7894737 , 0.84210528, 0.89473686, 0.94736844])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [37]:
b=np.arange(1,26)
b.resize(5,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [39]:
b=np.arange(12,24)
b.resize(3,4)
print(b)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [42]:
np.arange(20,21)

array([20])

In [47]:
list1=np.arange(2,13,5)
list1.resize(3,1)
print(list1)

[[ 2]
 [ 7]
 [12]]


In [43]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [44]:
s=np.arange(16,26)
s.resize(2,5)
print(s)

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [48]:
b=np.arange(1,11)
b.sum()

55

#### Get the standard deviation of the values in mat

In [51]:
b=np.arange(1,11)
b.std()

2.8722813232690143

#### Get the sum of all the columns in mat

In [53]:
b=np.arange(1,11)
b.resize(2,5)
b.sum(axis=0)

array([ 7,  9, 11, 13, 15])

# Great Job!