# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [12]:
import numpy as np
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [10]:
import numpy as np
arr=np.ones(10)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Create an array of 10 fives

In [16]:
arr[0:10]=5
arr[0:10]

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [21]:
import numpy as np
np.arange(10,51)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [24]:

for i in range(10,50,2):
 arr[i]=i

IndexError: index 10 is out of bounds for axis 0 with size 10

#### Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
arr=np.arange(0,9)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [33]:
np.random.rand(1)

array([0.04465331])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [34]:
np.random.randn(5,5)

array([[ 0.62763607, -1.22803052,  0.07621911, -0.37160811,  1.03418824],
       [-0.2295376 ,  1.09760593,  0.33007217, -0.50644491,  0.27443583],
       [ 0.63610497,  1.51655948,  0.54486054,  0.48979201, -1.25633312],
       [ 0.42099707,  0.13272639,  0.44072151,  0.38952033, -2.1060613 ],
       [-0.78724505, -0.59448903,  0.72113406,  0.76849456, -1.16217036]])

#### Create the following matrix:


In [56]:
arr=np.linspace(0.01,1,100)
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [49]:
np.linspace(0,1,18)

array([0.        , 0.05882353, 0.11764706, 0.17647059, 0.23529412,
       0.29411765, 0.35294118, 0.41176471, 0.47058824, 0.52941176,
       0.58823529, 0.64705882, 0.70588235, 0.76470588, 0.82352941,
       0.88235294, 0.94117647, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [72]:
arr=np.arange(1,26)
arr2=arr.reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
arr2[2:5,1:5]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [82]:
arrr=arr2[0:3,1:2]
arrr

array([[ 2],
       [ 7],
       [12]])

In [83]:
arrrr=arr2[5:5]

In [86]:
arrrr=arr2[4:5]
arrrr

array([[21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [87]:
np.sum(arr2)

325

#### Get the standard deviation of the values in mat

In [74]:
np.sd(arr2)

7.211102550927978

#### Get the sum of all the columns in mat

In [90]:
s=np.sum(arr2,axis=0)
s

array([55, 60, 65, 70, 75])

# Great Job!