# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
import numpy as np
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [ ]:
import numpy as np
array = np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
import numpy as np
array = np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [ ]:
array = np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [ ]:
array = np.arange(5,26)*2
print(array)
#print("\n")
#array = np.arange(10,51,2)
#print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
array = np.arange(0,9).reshape(3,3)
print(f"{array}")

array([[0 1 2]
 [3 4 5]
 [6 7 8]])


#### Create a 3x3 identity matrix

In [ ]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [ ]:
array = np.random.rand(1)
print(array)

[0.41255662]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
array = np.random.randn(5,5)
print(array)

[[-0.61262426  0.94185925  0.62479315 -0.10653443 -0.83857357]
 [ 0.48340641  0.74041124  0.43283558  0.4773477  -0.08507441]
 [ 0.8622321   0.58535987 -1.98316726 -1.51178118 -0.32634209]
 [ 0.25481857  1.0473229   0.308225    0.90993777  0.29444698]
 [-1.05852504 -0.29329638  0.21695969  1.27427054 -1.90801351]]


#### Create the following matrix:

In [ ]:
arr = np.arange(1,101)*(0.01)
barr = arr.reshape(10,10)
print(f"{barr}")

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
arr = np.random.rand(20)
print(arr)

[0.26096248 0.02107641 0.67486859 0.10386275 0.05550268 0.24533626
 0.36019701 0.33719858 0.29870901 0.60413395 0.51939545 0.38740843
 0.33390643 0.34310624 0.41374582 0.02996326 0.65067903 0.94275716
 0.80070208 0.76017774]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

20

array([[ 2],
       [ 7],
       [12]])

array([21, 22, 23, 24, 25])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

#### Get the standard deviation of the values in mat

7.211102550927978

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Great Job!