# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [13]:
np.random.rand(2)

array([0.80332477, 0.72941875])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [15]:
np.random.randn(25)

array([ 1.54961945,  0.8340789 , -0.62382144, -0.59309041,  1.4834839 ,
        0.32624433, -1.51122895,  0.7627391 ,  1.36387885, -0.32217801,
        0.9209524 , -0.33427343, -0.36476487, -0.01250033,  0.24700459,
        1.64422984,  0.25238603, -0.07516335, -0.04472781, -0.3945247 ,
       -1.20536644, -0.15846631, -0.93332664, -0.47914089,  1.23098573])

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [16]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [29]:
arr=np.arange(25)
arr=arr+1
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
arr=np

In [41]:
arr=[3,4,20]
print(arr[2])

20


In [45]:
arr=np.arange(2,13,5)
arr.reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [48]:
arr=np.arange(2,6)
arr.reshape(1,4)

array([[2, 3, 4, 5]])

### Now do the following

#### Get the sum of all the values in mat

In [52]:
arr=np.random.rand(25)
sum=0
for(i in range(25))
sum=sum+ arr[i]

SyntaxError: invalid syntax (1320855689.py, line 3)

#### Get the standard deviation of the values in mat

#### Get the sum of all the columns in mat

# Great Job!