# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [18]:
import numpy as np
a=np.zeros((1,10))
print('array initialized with all zeroes:', a)

array initialized with all zeroes: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Create an array of 10 ones

In [5]:
import numpy as np
a=np.ones((1,10))
print('array initialized with all ones:', a)

array initialized with all ones: [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### Create an array of 10 fives

In [8]:
import numpy as np
a=np.ones((1,10))*5
print('array',a)

array [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


#### Create an array of the integers from 10 to 50

In [9]:
import numpy as np
a=np.array(i for i in range(10,50))
print('array', a)

array <generator object <genexpr> at 0x0000011B3DE67048>


#### Create an array of all the even integers from 10 to 50

In [10]:
import numpy as np
a=np.array(i*2 for i in range(5,25))
print('array', a)

array <generator object <genexpr> at 0x0000011B3DE670C8>


#### Create a 3x3 matrix with values ranging from 0 to 8

In [1]:
import numpy as np
a=np.array(i for i in range(9))
print('array', a)

array <generator object <genexpr> at 0x00000242EB7263C8>


#### Create a 3x3 identity matrix

In [14]:
import numpy as np
a=np.identity(3,dtype=float)
print('array', a)

array [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [15]:
import numpy as np
a = np.random.normal(0,1,1)
print("array",a )


array [0.00432229]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [2]:
import numpy as np
a=np.random.random((5,5))
print('array', a)


array [[0.8668542  0.88904201 0.65823134 0.04510304 0.38928462]
 [0.95228356 0.52458801 0.52716057 0.9482643  0.76704324]
 [0.42398428 0.68643591 0.9002367  0.43535267 0.1998899 ]
 [0.26521033 0.62157366 0.86051952 0.37184316 0.58866845]
 [0.5969041  0.25793534 0.01549467 0.82602221 0.70241653]]


#### Create the following matrix:

In [20]:
import numpy as np
a=np.array(i*0.01 for i in range (1,10))
print('array', a)

array <generator object <genexpr> at 0x0000011B3DE67B48>


#### Create an array of 20 linearly spaced points between 0 and 1:

In [3]:
import numpy as np
a=np.linspace(0,1,20)
print('array', a)

array [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [4]:
import numpy as np
a=np.array(i for i in range(1,25))
print('array', a)

array <generator object <genexpr> at 0x00000242F37250C8>


In [5]:
import numpy as np
a=np.array([[12, 13, 14, 15],[17, 18, 19, 20],[22, 23, 24, 25] ], dtype = 'float')
print('array', a)

array [[12. 13. 14. 15.]
 [17. 18. 19. 20.]
 [22. 23. 24. 25.]]


20

In [6]:
import numpy as np
a= np.array([[2],[7],[12]])
print('array', a)

array [[ 2]
 [ 7]
 [12]]


In [7]:
import numpy as np
a=np.array([21, 22, 23, 24, 25])
print('array', a)

array [21 22 23 24 25]


In [8]:
import numpy as np
a=np.array([[16, 17, 18, 19, 20],[21, 22, 23, 24, 25] ])
print('array', a)

array [[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [12]:
import numpy as np
a=([55, 60, 65, 70, 75])
print('sum of array:', np.sum(a))

sum of array: 325


#### Get the standard deviation of the values in mat

In [11]:
import numpy as np
a=([55, 60, 65, 70, 75])
print('standard deviation of array:', np.std(a))

standard deviation of array: 7.0710678118654755


#### Get the sum of all the columns in mat

In [9]:
import numpy as np
a=([55, 60, 65, 70, 75])
print('sum of array:', np.sum(a))

sum of array: 325


# Great Job!