# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [10]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [32]:
x=np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [33]:
x=np.ones(10)
print(5*x)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [13]:
x=np.arange(10,51)
print(np.array(x))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [21]:
x=np.arange(10,51,2)
print(x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
x=np.arange(0,9)
x=np.array_split(x,3)
x=np.asmatrix(x)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [32]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [67]:
x=np.random.rand()
print(x)

0.8177083927186685


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [68]:
x=np.random.rand(25)
print(x)

[0.09198114 0.43863873 0.33114544 0.53773118 0.90335027 0.36312652
 0.49964409 0.96212894 0.24113973 0.29279996 0.58256741 0.61216358
 0.72922151 0.35226358 0.90977039 0.7548081  0.08081703 0.06920116
 0.91432682 0.16772317 0.76754391 0.9149673  0.6851767  0.27981325
 0.67525429]


#### Create the following matrix:

In [38]:
x=np.arange(0.01,1.01,0.01)
x.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [40]:
x=np.linspace(0,1.01,20)
x.reshape(4,5)

array([[0.        , 0.05315789, 0.10631579, 0.15947368, 0.21263158],
       [0.26578947, 0.31894737, 0.37210526, 0.42526316, 0.47842105],
       [0.53157895, 0.58473684, 0.63789474, 0.69105263, 0.74421053],
       [0.79736842, 0.85052632, 0.90368421, 0.95684211, 1.01      ]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
a=np.arange(1,26)
a.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
b=np.arange(12,24)
b.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
b=np.arange(21,26)
b.reshape(1,5)

array([[21, 22, 23, 24, 25]])

In [27]:
b=np.arange(21,26)
b.reshape(1,5)

array([[21, 22, 23, 24, 25]])

In [30]:
b=np.arange(16,26)
b.reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
b=np.arange(16,26)
b.reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [21]:
mat=a.reshape(5,5)
mat.sum()

325

#### Get the standard deviation of the values in mat

In [15]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [23]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

# Great Job!