In [1]:
# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

SyntaxError: invalid syntax (263658639.py, line 3)

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
array=np.zeros(10)

#### Create an array of 10 ones

In [4]:
array=np.ones(10)

#### Create an array of 10 fives

In [5]:
array=np.ones(10)*5

#### Create an array of the integers from 10 to 50

In [6]:
array=np.arange(10,51,1)

#### Create an array of all the even integers from 10 to 50

In [7]:
array=np.arange(10,51,2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
array=np.arange(0,9,1).reshape(1,3,3)

#### Create a 3x3 identity matrix

In [9]:
array=np.identity(3)

#### Use NumPy to generate a random number between 0 and 1

In [10]:
np.random.uniform(0,1,1)

array([0.28127825])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
np.random.uniform(-1,1,25)

array([-0.13567479,  0.22596044, -0.13397477, -0.91110887,  0.02525861,
       -0.84881329,  0.62657063, -0.97916136,  0.6513215 ,  0.4777094 ,
       -0.67524122,  0.60920187, -0.15892235, -0.66397954, -0.53095156,
        0.08844218, -0.85398573, -0.69029657,  0.02794804,  0.37506502,
       -0.96546099, -0.33889883, -0.4364305 , -0.51520327, -0.11668696])

#### Create the following matrix:

In [12]:
array=np.arange(0.01,1.01,0.01).reshape(10,10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [13]:
array=np.linspace(0,1,20)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [22]:
array=np.arange(1,26,1).reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
array[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [23]:
array[3,4]

20

In [25]:
array[:3,1].reshape(3,1)
    

array([[ 2],
       [ 7],
       [12]])

In [26]:
array[4,0:]

array([21, 22, 23, 24, 25])

In [27]:
array[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
x=np.sum(array)

#### Get the standard deviation of the values in mat

In [29]:
array.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [33]:
array.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!